[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mayo_spindles"
version = "0.0.1"
requires-python = ">=3.10"
authors = [
  {name = "Michal Sejak", email = "sejakm@kiv.zcu.cz"},
]
maintainers = [
  {name = "Michal Sejak", email = "sejakm@kiv.zcu.cz"},
]