c_in: 31
enc_in: 31
dec_in: 64
c_out: 64
seq_len: 7500
hidden_size: 64
activation: 'gelu'
num_layers: 2
share_bottleneck: true

# TSLib config

task_name: 'anomaly_detection'
label_len: 7500
pred_len: 7500
inverse: false
mask_rate: 1
anomaly_ratio: 1
top_k: 5
num_kernels: 6
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 2
d_ff: 2048
moving_avg: 25
factor: 1
distil: true
dropout: 0.1
output_attention: false
channel_independence: 0
p_hidden_dims: [128, 128]
p_hidden_layers: 2